# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cargarArchivo.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(354, 213)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 70, 47, 13))
        self.label.setObjectName("label")
        self.txtRuta = QtWidgets.QLineEdit(Dialog)
        self.txtRuta.setGeometry(QtCore.QRect(120, 70, 171, 20))
        self.txtRuta.setObjectName("txtRuta")
        self.buttonSelect = QtWidgets.QPushButton(Dialog)
        self.buttonSelect.setGeometry(QtCore.QRect(100, 120, 75, 23))
        self.buttonSelect.setObjectName("buttonSelect")
        self.buttonRegresar = QtWidgets.QPushButton(Dialog)
        self.buttonRegresar.setGeometry(QtCore.QRect(200, 120, 75, 23))
        self.buttonRegresar.setObjectName("buttonRegresar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Ruta"))
        self.buttonSelect.setText(_translate("Dialog", "Seleccionar"))
        self.buttonRegresar.setText(_translate("Dialog", "Regresar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
