# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menuPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(381, 336)
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 361, 81))
        self.textEdit.setObjectName("textEdit")
        self.buttonCargar = QtWidgets.QPushButton(Dialog,clicked = lambda: self.probando())
        self.buttonCargar.setGeometry(QtCore.QRect(130, 130, 121, 31))
        self.buttonCargar.setObjectName("buttonCargar")
        self.buttonCursos = QtWidgets.QPushButton(Dialog)
        self.buttonCursos.setGeometry(QtCore.QRect(130, 170, 121, 31))
        self.buttonCursos.setObjectName("buttonCursos")
        self.buttonCreditos = QtWidgets.QPushButton(Dialog)
        self.buttonCreditos.setGeometry(QtCore.QRect(130, 210, 121, 31))
        self.buttonCreditos.setObjectName("buttonCreditos")
        self.buttonSalir = QtWidgets.QPushButton(Dialog)
        self.buttonSalir.setGeometry(QtCore.QRect(130, 250, 121, 31))
        self.buttonSalir.setObjectName("buttonSalir")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
    def probando(self):
        self.textEdit.setText("lo cambie todo")
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Nombre del Curso: Laboratorio Lenguajes Formales y de Programación</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Nombre del Estudiante: Rubén Alejandro Ralda Mejia</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Carné del Estudiante: 202111835</p></body></html>"))
        self.buttonCargar.setText(_translate("Dialog", "Cargar Archivo"))
        self.buttonCursos.setText(_translate("Dialog", "Gestionar Cursos"))
        self.buttonCreditos.setText(_translate("Dialog", "Conteo de Créditos"))
        self.buttonSalir.setText(_translate("Dialog", "Salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
